name: UI Automation Tests

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run tests with Chrome Flags
      env:
        # Передаем конфигурацию для Chrome напрямую через переменные окружения Linux
        # Это заставит Chrome на сервере запуститься в режиме без экрана и без ограничений памяти
        MOZ_HEADLESS: 1
        CHROME_OPTIONS: "--headless=new --no-sandbox --disable-dev-shm-usage"
      run: |
        # Используем xvfb как подушку безопасности + запускаем pytest
        xvfb-run --server-args="-screen 0 1920x1080x24" pytest --alluredir=allure-results

    - name: Get Allure history
      continue-on-error: true
      uses: actions/checkout@v4
      with:
        ref: gh-pages
        path: gh-pages-dir

    - name: Allure Report Action
      uses: simple-elf/allure-report-action@master
      if: always()
      id: allure-report
      with:
        allure_results: allure-results
        allure_history: allure-history
        keep_reports: 20

    - name: Deploy Allure Report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: allure-history
        publish_branch: gh-pages